version: "3"

vars:
  GOFLAGS: ""

env:
  GO111MODULE: on

tasks:
  build:
    desc: Build gsbt binary
    deps: [schema]
    cmds:
      - go build {{.GOFLAGS}} ./cmd/gsbt

  schema:
    desc: Generate JSON configuration schema
    cmds:
      - go generate ./internal/config/...

  test:
    desc: Run unit tests
    cmds:
      - go test {{.GOFLAGS}} ./...

  run:
    desc: Run gsbt with arguments (pass args after --)
    cmds:
      - go run {{.GOFLAGS}} ./cmd/gsbt {{.CLI_ARGS}}
    vars:
      CLI_ARGS: "{{.CLI_ARGS}}"

  tidy:
    desc: Tidy go module dependencies
    cmds:
      - go mod tidy
