version: "3"

vars:
  GOFLAGS: ""

env:
  GO111MODULE: on

tasks:
  build:
    desc: Build gsbt binary
    deps: [schema]
    cmds:
      - go build {{.GOFLAGS}} ./cmd/gsbt

  schema:
    desc: Generate JSON configuration schema
    cmds:
      - go generate ./internal/config/...

  test:
    desc: Run unit tests
    cmds:
      - go test {{.GOFLAGS}} ./...

  run:
    desc: Run gsbt with arguments (pass args after --)
    cmds:
      - go run {{.GOFLAGS}} ./cmd/gsbt {{.CLI_ARGS}}
    vars:
      CLI_ARGS: "{{.CLI_ARGS}}"

  tidy:
    desc: Tidy go module dependencies
    cmds:
      - go mod tidy

  release:
    desc: "Create and push a new release tag (usage: task release VER=v1.0.0)"
    cmds:
      - |
        if [ -z "{{.VER}}" ]; then
          echo "Error: VER argument is required (e.g. task release VER=v1.0.0)"
          exit 1
        fi
        # Validate format (basic vX.Y.Z check)
        if [[ ! "{{.VER}}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
           echo "Warning: Version '{{.VER}}' does not match standard vX.Y.Z format"
           read -p "Continue anyway? [y/N] " -n 1 -r
           echo
           if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 1; fi
        fi

        # Check if tag exists locally
        if git rev-parse "{{.VER}}" >/dev/null 2>&1; then
          echo "Error: Tag {{.VER}} already exists locally"
          exit 1
        fi

        # Check if tag exists remotely
        if git ls-remote --tags origin | grep -q "refs/tags/{{.VER}}$"; then
          echo "Error: Tag {{.VER}} already exists on remote"
          exit 1
        fi

        # Validate goreleaser config if installed
        if command -v goreleaser >/dev/null 2>&1; then
          echo "Validating GoReleaser config..."
          goreleaser check || exit 1
        else
          echo "Warning: goreleaser not found, skipping config check."
        fi

        echo "Creating tag {{.VER}}..."
        git tag -a "{{.VER}}" -m "Release {{.VER}}"

        echo "Pushing tag to origin..."
        git push origin "{{.VER}}"
